---
title: "Voting"
author: "Kevin Wang"
date: "11/19/2019"
output: html_document
---

```{r setup, include=FALSE,warning=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidymodels)
library(skimr)
library(readr)
library(fs)
library(ggplot2)
```

```{r}
download.file("https://github.com/TheUpshot/2018-live-poll-results/archive/master.zip", destfile = "master.zip")

unzip("master.zip")

az1 <- read_csv("2018-live-poll-results-master/data/elections-poll-az02-1.csv",
              col_types = cols(
                .default = col_character(),
                turnout_scale = col_double(),
                turnout_score = col_double(),
                w_LV = col_double(),
                w_RV = col_double(),
                final_weight = col_double(),
                timestamp = col_datetime(format = "")
                )
              )
# Make sure that the warning will go away so col_types


#Read in all the files by making a list

file_list <- dir_ls("2018-live-poll-results-master/data/")

#MAP function to read it all in
voting <- map_dfr(file_list,.id="source", ~read_csv(.x),
                  col_types=cols(
                    .default = col_character(),
                    turnout_scale = col_double(),
                    turnout_score = col_double(),
                    w_LV = col_double(),
                    w_RV = col_double(),
                    final_weight = col_double(),
                    timestamp = col_datetime(format = "")
                    )
                  )

x <- voting %>%
  mutate(dvote=ifelse(response == "Dem",1,0)) %>%
  mutate(female= ifelse(gender== "Female",1,0)) %>%
  select(dvote, female, response, gender)
 
ggplot(x, aes(x=female,y=dvote)) +geom_jitter() +
  geom_smooth(method = "lm", se=FALSE)

glm_obj <- glm(dvote ~ female, data = x, family = "binomial")

my_data <- tibble(female = c(0, 0, 1))

x %>% 
  mutate(predict = predict(glm_obj, type = "response"))
```